### ISSUE TITLE
Disabling the plugin for selected items

### ISSUE THREAD

**Issue by lukaszkikowski** [suprraz/babel-plugin-react-element-info#5]
Hi!
Is it possible to disable this plugin for selected elements? In my project I use `<React.Fragment />` and I get this error:

```Warning: Invalid prop `data-qa-file` supplied to `React.Fragment`. React.Fragment can only have `key` and `children` props.```

Does anyone have any idea what to do about it?

**Comment by josephj** [comment]
I got the same issue and made a pull request #8 for this.

**Comment by suprraz** [comment]
Thanks @josephj !

**Comment by josephj** [comment]
No worries man. Btw will you do npm publish for this package soon? 😁
